version: "3"

services:
  db:
    image: postgres:14
    container_name: db_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpg
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data.sql:/docker-entrypoint-initdb.d/data.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MY_DATABASE_DRIVER: "postgres"
      DB_HOST: db
      DB_USER_NAME: root
      DB_NAME: database
      DB_PASSWORD: rootpg
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - 8081:3000
    restart: always
